kind: Project
apiVersion: monitoring.cattle.io/v1alpha1
metadata:
  name: p-default
  namespace: cattle-project-monitoring-system
spec:
  selector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: Exists
  alertmanager:
    enabled: true
  grafana:
    enabled: true