name: Docker Image CI

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Login Build Push
        run: |
          make charts
          make
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          export DOCKER_BUILDKIT=1
          docker images
          docker tag rancher/prometheus-federator:${VERSION} ghcr.io/${{ github.repository_owner }}/${IMAGE}:${VERSION}
          docker push ghcr.io/${{ github.repository_owner }}/${IMAGE}:${VERSION}
        env:
          IMAGE: prometheus-federator
          TAG: debug
